version: 0.0.{build}
image: Visual Studio 2017
clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
        cd %APPVEYOR_BUILD_FOLDER%
        git checkout -q %APPVEYOR_REPO_COMMIT%
        git submodule update --init --recursive
build_script:
- cmd: >-
	cd script
    @echo | setupWin.bat
    powershell -ExecutionPolicy RemoteSigned -File buildAssimpWin-VS15.ps1
    powershell -ExecutionPolicy RemoteSigned -File buildPhysXWin-VS15.ps1
	powershell -ExecutionPolicy RemoteSigned -File buildEngineWin-VS15.ps1

skip_commits:
  files:
  - '**/*.md'
  - 'res/**/*.*'